### PR TITLE
Add project to travis ci. Add travis badges to readme

### LINKED ISSUE #5: Add the project to travis
Add the project to travis
Make sure the tests run in travis
Add the travis badges to the readme

### PR DESCRIPTION
**Pull request by benjaminettori**
versions 0.8 and 0.6 of node had failing builds. Removed them from travis yml file.
closes #5

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
@benjaminettori could you squash these 4 commits into one commit? If you've never done that, read [Git Interactive Rebase, Squash, Amend and Other Ways of Rewriting History](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) and give it a try. If you get stuck, let's look at it during tomorrow's meeting.

**Comment by benjaminettori** [comment]
The commits were combined into 1. Thanks for the reference.

**Comment by benjaminettori** [comment]
FYI, I assume we will need to enable  CfABrigadePhiladelphia/jawn in Travis. Right now, the travis badge is pointing to my forked repo. I don't have admin rights to do this on the main repo.

image

**Comment by flyingzumwalt** [comment]
@benjaminettori thanks for catching that. I've enabled travis and updated the badge.

**Pull request merged**
