### PR TITLE
Return stream from import.js

### PR DESCRIPTION
**Pull request by benjaminettori**

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
:+1: I like this approach better than using `miss.pipe`. The code in the test looks much more like what we wanted to write initially. I think the main thing that tripped us up before (other than not really understanding streams) was that we wrote our test to listen for an `end` event when it needed to listen for `finish` events like you did in line 16 of test/import.js

@wtkm7 do you have opinions on this? Want to merge it?

**Comment by flyingzumwalt** [comment]
@benjaminettori It looks like there are a bunch of extra commits on this PR's branch. Do you know why they're showing up?

**Comment by benjaminettori** [comment]
@flyingzumwalt I think they are showing up because I had to rebase my repo when getting the latest commits from the main repo.

**Comment by flyingzumwalt** [comment]
Could you squash the commits down to one with a message like `use miss.pipeline to return a stream`?

**Comment by mels065** [comment]
:+1: @benjaminettori I'm ready to merge this once you've squashed down the commits

**Comment by benjaminettori** [comment]
@mels065 Ok I have squashed the commits as much as I can. It may be possible to squash them further after the merge.

**Pull request merged**
