### PR TITLE
Added NPM badge to README.md

### PR DESCRIPTION
**Pull request by CameronSima**

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
@CameronSima you can make that 'merge' commit go away by rebasing against the CfABrigadePhiladelphia master branch.

Try this out.  If it doesn't work, we'll just merge your PR as-is.

## Rebasing against the shared master branch

Add the shared code base as a remote. Pick any name. I'm calling it 'shared'

```
git add remote shared git@github.com:CfABrigadePhiladelphia/jawn.git
```

Just in case something goes  wrong, do these next steps on a new branch. I'm calling the branch mysandbox

```
git checkout -b mysandbox
```

Then fetch the latest contents of the 'shared' repo and then rebase against its master branch.

```
git fetch shared
git rebase shared/master
```

This will pull down the current contents of the main/shared repo and then re-run each of your commits on top of it.  This is an interactive process. When it tries to run your second commit, the 'merge' commit that we want to get rid of, it _should_ say "nothing to commit".  If it says that, you can run `git rebase --skip` and then the rebase will finish.

At that point, take a look at your code and make sure everything is there.
Then run `git log`. You should just see one commit from you.

If it's all correct, then throw away your old `master` branch and replace it with `mysandbox`.

```
git branch -m master old-master
git branch -m mysandbox master
```

Then force-push to _your_ github repo

```
git push -f origin master
```

Now look at the pull request.  Does everything look right? Did the 'merge' commit go away?

If everything looks good, you can delete your old master branch.

```
git branch -D old-master
```

**Comment by CameronSima** [comment]
I'm getting `Permission denied (publickey). fatal: Could not read from the remote repository` at `git fetch shared`

**Comment by flyingzumwalt** [comment]
Ah. you have to accept the invitation to the dat-jawn team. You should have gotten an email last night.

**Comment by flyingzumwalt** [comment]
Or you can use the https address for the shared repo, which lets you point at a remote repo that you only have read permission  on.

```
git remote set-url shared https://github.com/CfABrigadePhiladelphia/jawn.git
```

**Comment by flyingzumwalt** [comment]
Well done. This will be a good example to use next week (or the week after) when we talk about branches and rebasing.

**Comment by flyingzumwalt** [comment]
Oops. I closed it too soon!

**Pull request merged**
